services:
  postgres:
    image: postgres
    container_name: streamo_postgres
    restart: unless-stopped
    env_file:
      - environments/${ENVIRONMENT:-development}/.env.database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamo-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 10

  streamo-api:
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
            - dist/
            - .git/
        - action: rebuild
          path: package.json
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamo_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - environments/${ENVIRONMENT:-development}/.env.database
      - environments/${ENVIRONMENT:-development}/.env.app
    networks:
      - streamo-network

volumes:
  postgres_data:

networks:
  streamo-network:
    driver: bridge
